name: DeadCrafterCore
version: 1.0
author: JonnyMine25
main: de.DeadCrafterCore.Main

commands:
  freeze:
    description: Freezet einen Spieler.
    usage: /<command> <player>
  prom:
    description: Promotet einen Spieler.
    usage: /<command> <player> <group>
  pw:
    description: Promotet den Neuling zum Spieler.
    usage: /<command> <password>
    aliases: [apply]
  mute:
    description: Mutet jemanden.
    usage: /<command> <player>
  broadcast:
    description: Broadcastet eine Message.
    usage: /<command> <message>
    aliases: [bc]
  ban:
    description: Bannt einen Spieler.
    usage: /<command> <player> [reason]